/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/saima-s/data-restore/pkg/apis/saima.dev.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDataRestores implements DataRestoreInterface
type FakeDataRestores struct {
	Fake *FakeSaimaV1
	ns   string
}

var datarestoresResource = v1.SchemeGroupVersion.WithResource("datarestores")

var datarestoresKind = v1.SchemeGroupVersion.WithKind("DataRestore")

// Get takes name of the dataRestore, and returns the corresponding dataRestore object, and an error if there is any.
func (c *FakeDataRestores) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.DataRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(datarestoresResource, c.ns, name), &v1.DataRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DataRestore), err
}

// List takes label and field selectors, and returns the list of DataRestores that match those selectors.
func (c *FakeDataRestores) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DataRestoreList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(datarestoresResource, datarestoresKind, c.ns, opts), &v1.DataRestoreList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.DataRestoreList{ListMeta: obj.(*v1.DataRestoreList).ListMeta}
	for _, item := range obj.(*v1.DataRestoreList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dataRestores.
func (c *FakeDataRestores) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(datarestoresResource, c.ns, opts))

}

// Create takes the representation of a dataRestore and creates it.  Returns the server's representation of the dataRestore, and an error, if there is any.
func (c *FakeDataRestores) Create(ctx context.Context, dataRestore *v1.DataRestore, opts metav1.CreateOptions) (result *v1.DataRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(datarestoresResource, c.ns, dataRestore), &v1.DataRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DataRestore), err
}

// Update takes the representation of a dataRestore and updates it. Returns the server's representation of the dataRestore, and an error, if there is any.
func (c *FakeDataRestores) Update(ctx context.Context, dataRestore *v1.DataRestore, opts metav1.UpdateOptions) (result *v1.DataRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(datarestoresResource, c.ns, dataRestore), &v1.DataRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DataRestore), err
}

// Delete takes name of the dataRestore and deletes it. Returns an error if one occurs.
func (c *FakeDataRestores) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(datarestoresResource, c.ns, name, opts), &v1.DataRestore{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDataRestores) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(datarestoresResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.DataRestoreList{})
	return err
}

// Patch applies the patch and returns the patched dataRestore.
func (c *FakeDataRestores) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DataRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(datarestoresResource, c.ns, name, pt, data, subresources...), &v1.DataRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DataRestore), err
}
