/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	saimadevcomv1 "github.com/saima-s/data-restore/pkg/apis/saima.dev.com/v1"
	versioned "github.com/saima-s/data-restore/pkg/client/clientset/versioned"
	internalinterfaces "github.com/saima-s/data-restore/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/saima-s/data-restore/pkg/client/listers/saima.dev.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DataRestoreInformer provides access to a shared informer and lister for
// DataRestores.
type DataRestoreInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DataRestoreLister
}

type dataRestoreInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDataRestoreInformer constructs a new informer for DataRestore type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDataRestoreInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDataRestoreInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDataRestoreInformer constructs a new informer for DataRestore type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDataRestoreInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SaimaV1().DataRestores(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SaimaV1().DataRestores(namespace).Watch(context.TODO(), options)
			},
		},
		&saimadevcomv1.DataRestore{},
		resyncPeriod,
		indexers,
	)
}

func (f *dataRestoreInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDataRestoreInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dataRestoreInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&saimadevcomv1.DataRestore{}, f.defaultInformer)
}

func (f *dataRestoreInformer) Lister() v1.DataRestoreLister {
	return v1.NewDataRestoreLister(f.Informer().GetIndexer())
}
