/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/saima-s/data-restore/pkg/apis/saima.dev.com/v1"
	scheme "github.com/saima-s/data-restore/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DataRestoresGetter has a method to return a DataRestoreInterface.
// A group's client should implement this interface.
type DataRestoresGetter interface {
	DataRestores(namespace string) DataRestoreInterface
}

// DataRestoreInterface has methods to work with DataRestore resources.
type DataRestoreInterface interface {
	Create(ctx context.Context, dataRestore *v1.DataRestore, opts metav1.CreateOptions) (*v1.DataRestore, error)
	Update(ctx context.Context, dataRestore *v1.DataRestore, opts metav1.UpdateOptions) (*v1.DataRestore, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.DataRestore, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.DataRestoreList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DataRestore, err error)
	DataRestoreExpansion
}

// dataRestores implements DataRestoreInterface
type dataRestores struct {
	client rest.Interface
	ns     string
}

// newDataRestores returns a DataRestores
func newDataRestores(c *SaimaV1Client, namespace string) *dataRestores {
	return &dataRestores{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dataRestore, and returns the corresponding dataRestore object, and an error if there is any.
func (c *dataRestores) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.DataRestore, err error) {
	result = &v1.DataRestore{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("datarestores").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DataRestores that match those selectors.
func (c *dataRestores) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DataRestoreList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DataRestoreList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("datarestores").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dataRestores.
func (c *dataRestores) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("datarestores").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dataRestore and creates it.  Returns the server's representation of the dataRestore, and an error, if there is any.
func (c *dataRestores) Create(ctx context.Context, dataRestore *v1.DataRestore, opts metav1.CreateOptions) (result *v1.DataRestore, err error) {
	result = &v1.DataRestore{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("datarestores").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dataRestore).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dataRestore and updates it. Returns the server's representation of the dataRestore, and an error, if there is any.
func (c *dataRestores) Update(ctx context.Context, dataRestore *v1.DataRestore, opts metav1.UpdateOptions) (result *v1.DataRestore, err error) {
	result = &v1.DataRestore{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("datarestores").
		Name(dataRestore.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dataRestore).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dataRestore and deletes it. Returns an error if one occurs.
func (c *dataRestores) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("datarestores").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dataRestores) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("datarestores").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dataRestore.
func (c *dataRestores) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DataRestore, err error) {
	result = &v1.DataRestore{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("datarestores").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
