/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/saima-s/data-restore/pkg/apis/saima.dev.com/v1"
	scheme "github.com/saima-s/data-restore/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DataSnapshotsGetter has a method to return a DataSnapshotInterface.
// A group's client should implement this interface.
type DataSnapshotsGetter interface {
	DataSnapshots(namespace string) DataSnapshotInterface
}

// DataSnapshotInterface has methods to work with DataSnapshot resources.
type DataSnapshotInterface interface {
	Create(ctx context.Context, dataSnapshot *v1.DataSnapshot, opts metav1.CreateOptions) (*v1.DataSnapshot, error)
	Update(ctx context.Context, dataSnapshot *v1.DataSnapshot, opts metav1.UpdateOptions) (*v1.DataSnapshot, error)
	UpdateStatus(ctx context.Context, dataSnapshot *v1.DataSnapshot, opts metav1.UpdateOptions) (*v1.DataSnapshot, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.DataSnapshot, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.DataSnapshotList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DataSnapshot, err error)
	DataSnapshotExpansion
}

// dataSnapshots implements DataSnapshotInterface
type dataSnapshots struct {
	client rest.Interface
	ns     string
}

// newDataSnapshots returns a DataSnapshots
func newDataSnapshots(c *SaimaV1Client, namespace string) *dataSnapshots {
	return &dataSnapshots{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dataSnapshot, and returns the corresponding dataSnapshot object, and an error if there is any.
func (c *dataSnapshots) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.DataSnapshot, err error) {
	result = &v1.DataSnapshot{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("datasnapshots").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DataSnapshots that match those selectors.
func (c *dataSnapshots) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DataSnapshotList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DataSnapshotList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("datasnapshots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dataSnapshots.
func (c *dataSnapshots) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("datasnapshots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dataSnapshot and creates it.  Returns the server's representation of the dataSnapshot, and an error, if there is any.
func (c *dataSnapshots) Create(ctx context.Context, dataSnapshot *v1.DataSnapshot, opts metav1.CreateOptions) (result *v1.DataSnapshot, err error) {
	result = &v1.DataSnapshot{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("datasnapshots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dataSnapshot).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dataSnapshot and updates it. Returns the server's representation of the dataSnapshot, and an error, if there is any.
func (c *dataSnapshots) Update(ctx context.Context, dataSnapshot *v1.DataSnapshot, opts metav1.UpdateOptions) (result *v1.DataSnapshot, err error) {
	result = &v1.DataSnapshot{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("datasnapshots").
		Name(dataSnapshot.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dataSnapshot).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *dataSnapshots) UpdateStatus(ctx context.Context, dataSnapshot *v1.DataSnapshot, opts metav1.UpdateOptions) (result *v1.DataSnapshot, err error) {
	result = &v1.DataSnapshot{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("datasnapshots").
		Name(dataSnapshot.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dataSnapshot).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dataSnapshot and deletes it. Returns an error if one occurs.
func (c *dataSnapshots) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("datasnapshots").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dataSnapshots) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("datasnapshots").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dataSnapshot.
func (c *dataSnapshots) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DataSnapshot, err error) {
	result = &v1.DataSnapshot{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("datasnapshots").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
