/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// DataRestoreListerExpansion allows custom methods to be added to
// DataRestoreLister.
type DataRestoreListerExpansion interface{}

// DataRestoreNamespaceListerExpansion allows custom methods to be added to
// DataRestoreNamespaceLister.
type DataRestoreNamespaceListerExpansion interface{}

// DataSnapshotListerExpansion allows custom methods to be added to
// DataSnapshotLister.
type DataSnapshotListerExpansion interface{}

// DataSnapshotNamespaceListerExpansion allows custom methods to be added to
// DataSnapshotNamespaceLister.
type DataSnapshotNamespaceListerExpansion interface{}
